### ISSUE TITLE
How is Go not building everything?

### ISSUE THREAD

**Issue by mimoo** [minio/blake2b-simd#27]
Hello!

Thanks for your library :) it's awesome. I had two questions on the code and I couldn't find a way to contact you beside github issues:

1. how can you run a function outside of the body [here](https://github.com/minio/blake2b-simd/blob/master/cpuid.go#L25:27) (I usually see that in an init() function)
1. how will all the files build if the instructions are not supported/missing? The following files are all built on amd64 architectures:
	- `compressAvx2_amd64.s`
	- `compressAvx_amd64.s`
	- `compressSse_amd64.s`

EDIT: For 2. I think I see an answer. Correct me if I'm wrong, but since you do not call the instructions directly but with BYTE (ex. `BYTE $0xc4; BYTE $0xc1; BYTE $0x1d; BYTE $0x6c; BYTE $0xe5`) then the compiler is fine. Although I'm guessing Go's compiler is fine with any instructions anyway, as long as you don't call them in your running code if your architecture doesn't support these instructions.

**Comment by harshavardhana** [comment]
> how can you run a function outside of the body here (I usually see that in an init() function)

This is a Go feature



> how will all the files build if the instructions are not supported/missing? The following files are all built on amd64 architectures:
> compressAvx2_amd64.s
> compressAvx_amd64.s
> compressSse_amd64.s

This is a go compiler feature.

**Comment by mimoo** [comment]
> This is a Go feature

I see, is this the same as writing them in an `init()` function? [The official golang blake2 implementation uses init](https://github.com/golang/crypto/blob/master/blake2b/blake2bAVX2_amd64.go#L9:L12)

**Comment by harshavardhana** [comment]
> I see, is this the same as writing them in an init() function? The official golang blake2 implementation uses init

Yes that is correct @mimoo

**Comment by mimoo** [comment]
Awesome! Thanks for the answer.
