### ISSUE TITLE
Binaries Wanted

### ISSUE THREAD

**Issue by alex-ilin** [minio/blake2b-simd#28]
Hello!

  I'm not a Go developer, but I'm really interested in the work that you've done here.
  Would it be possible for you to create a Windows console app (32- and 64-bit, if possible) from your source? I'm looking for a better version of b2sum.exe that comes with GNU CoreUtils.

**Comment by fwessels** [comment]
Unfortunately we do not build binaries. However it is very simple to get the Golang environment installed and then build it yourself.
