### ISSUE TITLE
Enhancement request: encoding.BinaryMarshaler and encoding.BinaryUnmarshaler interfaces

### ISSUE THREAD

**Issue by jerrymccollom** [minio/blake2b-simd#30]
We'll soon need to implement these interfaces as encouraged for Go 1.10, it would be nice to have them as an enhancement now in the official minio project as I would like to use this in my own project.  I submitted a PR with my cut at an implemention, but I know the authors would likely have a more optimal approach.

Thanks very much!

**Comment by kannappanr** [comment]
The related PR for reference is https://github.com/minio/blake2b-simd/pull/29

**Comment by harshavardhana** [comment]
Already support available in upstream code golang.org/x/crypto/blake2b
